spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.176:3306/test?serverTimezone=UTC
    username: root
    password: 123456
  main:
    #一个实体类对应多张表,覆盖
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      # 主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID(数字类型唯一ID)", UUID:"全局唯一ID UUID"
      id-type: auto
      # 字段策略 IGNORED:"忽略判断", NOT_NULL:"非 NULL 判断"), NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      # 驼峰下划线转换
      column-underline: true
      # 数据库类型
      db-type: MYSQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启mybatis驼峰命名
    map-underscore-to-camel-case: true
    # 关闭缓存
    cache-enabled: false
    #mybatis默认会走本地缓存(一级缓存)，清空localCache
    local-cache-scope: statement
    jdbc-type-for-null: 'null' #注意：单引号

