server:
  port: 9000

spring:
  application:
    name: demo-gateway
  cloud:
    consul:
      host: 192.168.2.176
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        service-name: ${spring.application.name}
        register: true
        health-check-interval: 5s
        health-check-path: /actuator/health
        register-health-check: true
        metadata:
          key1: value1
          key2: value2
        prefer-ip-address: true

    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能,利用微服务名进行路由
          enabled: true
      enabled: true
      routes:
       - id: gateway-doc
         uri: https://www.bilibili.com/
         predicates:
           - Path=/test
  boot:
    admin:
      discovery:
        ignored-services: consul

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
