server:
  port: 8000
spring:
  application:
    name: auth-center
  cloud:
    consul:
      host: 192.168.2.176
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        service-name: ${spring.application.name}
        register: true
        health-check-interval: 5s
        health-check-path: /actuator/health
        register-health-check: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:19000
        instance:
          prefer-ip: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

management:
  endpoints:
    # 开启所有端点
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app-name: @project.artifactId@
  app-version: @project.version@
