spring:
  h2:
    console:
      path: /h2
      settings:
        trace: false
        web-allow-others: true
        web-admin-password: root
      enabled: true
  datasource:
    url: jdbc:h2:./data/he;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: ALWAYS
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
  application:
    name: junit5-h2
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

info:
  application: ${spring.application.name}
  artifact: @project.artifactId@
  verion: @project.version@
